#!/bin/bash
# Quick Deployment Commands for Policy Navigator

echo "🚀 Policy Navigator - Quick Deploy Commands"
echo "============================================"
echo ""

# Replace YOUR_USERNAME with your actual GitHub username
GITHUB_USERNAME="YOUR_USERNAME"

echo "📋 Step 1: Push to GitHub"
echo "Run these commands one by one:"
echo ""
echo "git remote add origin https://github.com/$GITHUB_USERNAME/policy-navigator.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "============================================"
echo ""
echo "✅ After pushing to GitHub, follow these steps:"
echo ""
echo "🌐 Deploy Frontend (Vercel):"
echo "1. Go to https://vercel.com/"
echo "2. Sign in with GitHub"
echo "3. Click 'Add New...' → 'Project'"
echo "4. Select 'policy-navigator' repository"
echo "5. Root Directory: 'frontend'"
echo "6. Framework: Vite"
echo "7. Click 'Deploy'"
echo ""
echo "⚙️ Deploy Backend (Render):"
echo "1. Go to https://render.com/"
echo "2. Sign in with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Select 'policy-navigator' repository"
echo "5. Build Command: cd backend && pip install -r requirements.txt"
echo "6. Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "7. Add Environment Variable: OPENAI_API_KEY"
echo "8. Click 'Create Web Service'"
echo ""
echo "============================================"
echo ""
echo "📖 For detailed instructions, see DEPLOYMENT.md"
echo ""
